before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - 386
    - arm
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'
    - goos: windows
      goarch: 'arm64'

  binary: '{{ .ProjectName }}'
  main: cmd/chaos/chaos.go

archives:
- format: zip
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256

snapcrafts:
  - id: chaos
    replacements:
      darwin: macOS
    name: chaos
    publish: false
    summary: Go client to communicate with Chaos dataset API.
    description: |
      Go client to communicate with Chaos dataset API.
    grade: stable
    confinement: strict
    license: MIT
    base: core18
    apps:
      chaos:
        command: chaos
        plugs:
          - home
          - network
          - removable-media
          - dot-chaos
    plugs:
      dot-chaos:
        interface: personal-files
        write:
          - $HOME/.config/chaos